SELECT ID, VEICULO FROM VEICULOS ;

DELETE FROM VEICULOS;

SELECT * FROM veiculos;

INSERT INTO VEICULOS (ID, VEICULO) VALUES (1, 'Automóvel');

UPDATE VEICULOS SET VEICULO = 'Automóvel' WHERE ID = 1;

UPDATE VEICULOS SET ID = 3 WHERE ID = 1;
